"""add extended fields for works and compositions

Revision ID: 0cd54dea898f
Revises: c6ebe091056b
Create Date: 2025-11-25 09:27:44.845661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd54dea898f'
down_revision: Union[str, Sequence[str], None] = 'c6ebe091056b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compositions', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('compositions', sa.Column('tonality', sa.String(), nullable=True))
    op.create_index(op.f('ix_compositions_sort_order'), 'compositions', ['sort_order'], unique=False)
    op.add_column('works', sa.Column('tonality', sa.String(), nullable=True))
    op.add_column('works', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('works', sa.Column('nickname', sa.String(), nullable=True))
    op.create_index(op.f('ix_works_genre'), 'works', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_genre'), table_name='works')
    op.drop_column('works', 'nickname')
    op.drop_column('works', 'genre')
    op.drop_column('works', 'tonality')
    op.drop_index(op.f('ix_compositions_sort_order'), table_name='compositions')
    op.drop_column('compositions', 'tonality')
    op.drop_column('compositions', 'sort_order')
    # ### end Alembic commands ###
