"""Initial migration with slugs

Revision ID: 1678e6b60e3d
Revises: 
Create Date: 2025-11-20 00:19:26.994641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1678e6b60e3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('year_born', sa.Integer(), nullable=True),
    sa.Column('year_died', sa.Integer(), nullable=True),
    sa.Column('portrait_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_composers_id'), 'composers', ['id'], unique=False)
    op.create_index(op.f('ix_composers_name'), 'composers', ['name'], unique=True)
    op.create_index(op.f('ix_composers_name_ru'), 'composers', ['name_ru'], unique=False)
    op.create_index(op.f('ix_composers_slug'), 'composers', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_name'), 'playlists', ['name'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_year_end', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cover_art_url', sa.String(), nullable=True),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_index(op.f('ix_works_name'), 'works', ['name'], unique=False)
    op.create_index(op.f('ix_works_name_ru'), 'works', ['name_ru'], unique=False)
    op.create_index(op.f('ix_works_slug'), 'works', ['slug'], unique=True)
    op.create_table('compositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_original', sa.String(), nullable=True),
    sa.Column('catalog_number', sa.String(), nullable=True),
    sa.Column('composition_year', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cover_art_url', sa.String(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compositions_catalog_number'), 'compositions', ['catalog_number'], unique=False)
    op.create_index(op.f('ix_compositions_id'), 'compositions', ['id'], unique=False)
    op.create_index(op.f('ix_compositions_slug'), 'compositions', ['slug'], unique=True)
    op.create_index(op.f('ix_compositions_title'), 'compositions', ['title'], unique=False)
    op.create_index(op.f('ix_compositions_title_ru'), 'compositions', ['title_ru'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performers', sa.String(), nullable=True),
    sa.Column('recording_year', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['compositions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_recordings_file_hash'), 'recordings', ['file_hash'], unique=True)
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    op.create_table('playlist_recording',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('recording_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'recording_id')
    )
    op.create_table('recording_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recording_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording_favorites')
    op.drop_table('playlist_recording')
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_file_hash'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_compositions_title_ru'), table_name='compositions')
    op.drop_index(op.f('ix_compositions_title'), table_name='compositions')
    op.drop_index(op.f('ix_compositions_slug'), table_name='compositions')
    op.drop_index(op.f('ix_compositions_id'), table_name='compositions')
    op.drop_index(op.f('ix_compositions_catalog_number'), table_name='compositions')
    op.drop_table('compositions')
    op.drop_index(op.f('ix_works_slug'), table_name='works')
    op.drop_index(op.f('ix_works_name_ru'), table_name='works')
    op.drop_index(op.f('ix_works_name'), table_name='works')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_playlists_name'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_composers_slug'), table_name='composers')
    op.drop_index(op.f('ix_composers_name_ru'), table_name='composers')
    op.drop_index(op.f('ix_composers_name'), table_name='composers')
    op.drop_index(op.f('ix_composers_id'), table_name='composers')
    op.drop_table('composers')
    # ### end Alembic commands ###
