"""add is_no_catalog flag

Revision ID: 33b750edc7fd
Revises: 0cd54dea898f
Create Date: 2025-11-26 23:41:45.114863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b750edc7fd'
down_revision: Union[str, Sequence[str], None] = '0cd54dea898f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compositions', sa.Column('is_no_catalog', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('is_no_catalog', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'is_no_catalog')
    op.drop_column('compositions', 'is_no_catalog')
    # ### end Alembic commands ###
