"""Add scores table

Revision ID: 388128428a36
Revises: 8bfa61677ff0
Create Date: 2025-12-29 15:56:33.149069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388128428a36'
down_revision: Union[str, Sequence[str], None] = '8bfa61677ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_type', sa.String(), nullable=False),
    sa.Column('editor', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('source_text', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('composition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composition_id'], ['compositions.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_id'))

    op.drop_table('scores')
    # ### end Alembic commands ###
