"""Add lead_performer to recording

Revision ID: 4afc1f77262f
Revises: 8bd412f84743
Create Date: 2025-12-12 10:09:40.626702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afc1f77262f'
down_revision: Union[str, Sequence[str], None] = '8bd412f84743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('lead_performer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'lead_performer')
    # ### end Alembic commands ###
