"""add birth city coordinates

Revision ID: 58b6bf2efb62
Revises: 5a701ab1c360
Create Date: 2025-12-08 09:01:11.682183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b6bf2efb62'
down_revision: Union[str, Sequence[str], None] = '5a701ab1c360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composers', sa.Column('place_of_birth', sa.String(), nullable=True))
    op.add_column('composers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('composers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('composers', 'longitude')
    op.drop_column('composers', 'latitude')
    op.drop_column('composers', 'place_of_birth')
    # ### end Alembic commands ###
