"""add seo fields

Revision ID: 5a701ab1c360
Revises: 3312a574cbf9
Create Date: 2025-12-01 08:07:21.019537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a701ab1c360'
down_revision: Union[str, Sequence[str], None] = '3312a574cbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('meta_description', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('meta_keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'meta_keywords')
    op.drop_column('posts', 'meta_description')
    # ### end Alembic commands ###
