"""Add is_from_collection to Playlist

Revision ID: 6677a44e15d9
Revises: 6c0cbc2f34cd
Create Date: 2025-12-29 12:39:05.186464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6677a44e15d9'
down_revision: Union[str, Sequence[str], None] = '6c0cbc2f34cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_from_collection', sa.Boolean(), nullable=True))
        batch_op.alter_column('is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('is_from_collection')

    # ### end Alembic commands ###
