"""Add Genre table and link to Work

Revision ID: 696fa0548643
Revises: 4afc1f77262f
Create Date: 2025-12-19 11:54:26.261940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696fa0548643'
down_revision: Union[str, Sequence[str], None] = '4afc1f77262f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('genres',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )

    # === ЭТАП 1: Добавляем новое, не трогая старое ===
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_works_genre_id_genres",
            'genres',
            ['genre_id'],
            ['id']
        )

    # === ЭТАП 2: Теперь, когда все зависимости созданы, удаляем старую колонку ===
    with op.batch_alter_table('works', schema=None) as batch_op:
        # УДАЛЯЕМ ИНДЕКС ПЕРЕД УДАЛЕНИЕМ КОЛОНКИ
        batch_op.drop_index('ix_works_genre')
        batch_op.drop_column('genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Выполняем в обратном порядке
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), nullable=True))
        # Создаем индекс обратно
        batch_op.create_index('ix_works_genre', ['genre'], unique=False)

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_constraint("fk_works_genre_id_genres", type_='foreignkey')
        batch_op.drop_column('genre_id')

    op.drop_table('genres')
    # ### end Alembic commands ###