"""Add publisher to recordings

Revision ID: 6cf470f74f95
Revises: 388128428a36
Create Date: 2026-01-03 12:30:12.607281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf470f74f95'
down_revision: Union[str, Sequence[str], None] = '388128428a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publisher', sa.String(), nullable=True))

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('source_text',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('source_text',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_column('publisher')

    # ### end Alembic commands ###
