"""Add catalog_number to Work

Revision ID: 738c95ba457e
Revises: 33a58ce4782b
Create Date: 2025-11-21 08:40:27.477283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738c95ba457e'
down_revision: Union[str, Sequence[str], None] = '33a58ce4782b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('catalog_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_works_catalog_number'), 'works', ['catalog_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_catalog_number'), table_name='works')
    op.drop_column('works', 'catalog_number')
    # ### end Alembic commands ###
