"""Add details to recording model

Revision ID: 8bd412f84743
Revises: 20f77532371c
Create Date: 2025-12-12 09:13:26.619555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd412f84743'
down_revision: Union[str, Sequence[str], None] = '20f77532371c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('conductor', sa.String(), nullable=True))
    op.add_column('recordings', sa.Column('license', sa.String(), nullable=True))
    op.add_column('recordings', sa.Column('source_text', sa.String(), nullable=True))
    op.add_column('recordings', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'source_url')
    op.drop_column('recordings', 'source_text')
    op.drop_column('recordings', 'license')
    op.drop_column('recordings', 'conductor')
    # ### end Alembic commands ###
