"""Add cover_image_url to playlists

Revision ID: 8bfa61677ff0
Revises: f7d889443ed9
Create Date: 2025-12-29 13:31:27.163681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfa61677ff0'
down_revision: Union[str, Sequence[str], None] = 'f7d889443ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(), nullable=True))
        batch_op.alter_column('is_from_collection',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('is_from_collection',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
