"""Add system playlists

Revision ID: b98483270a6e
Revises: 5bea257fc452
Create Date: 2025-12-29 08:21:14.976629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98483270a6e'
down_revision: Union[str, Sequence[str], None] = '5bea257fc452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_playlists_is_system'), ['is_system'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_is_system'))
        batch_op.drop_column('is_system')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
