"""add youtube_url to recordings

Revision ID: c6ebe091056b
Revises: d8b7b9a3fbe5
Create Date: 2025-11-21 10:27:03.291923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ebe091056b'
down_revision: Union[str, Sequence[str], None] = 'd8b7b9a3fbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('youtube_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'youtube_url')
    # ### end Alembic commands ###
